# Generated by Django 4.2.3 on 2023-07-09 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keraladm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('startingrate', models.IntegerField()),
                ('offer', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='productimage')),
            ],
        ),
        migrations.AlterField(
            model_name='detailm',
            name='link',
            field=models.URLField(max_length=100),
        ),
    ]
