# Generated by Django 4.2.3 on 2023-07-09 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_keraladm_alter_detailm_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keraladm',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='keraladm',
            name='name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='keraladm',
            name='offer',
            field=models.CharField(max_length=1000),
        ),
    ]
